//Dinh nghia cac chan cua LCD
#use standard_io(C)
#use standard_io(D)
#define LCD_RS PIN_D1
#define LCD_RW PIN_D2
#define LCD_EN PIN_D3

#define LCD_D4 PIN_D4
#define LCD_D5 PIN_D5
#define LCD_D6 PIN_D6
#define LCD_D7 PIN_D7


//Dinh nghia chan tin hieu cua cam bien nhiet do
#define ONE_WIRE_PIN PIN_C1

//Dinh nghia chan tin hieu cua Relay
#define RELAY_SIG PIN_C6

//Dinh nghia cac chan cua ban phim
#define ONE PIN_B0
#define TWO PIN_B1
#define THREE PIN_B2
#define SETUP_EXIT PIN_E0
#define FOUR PIN_B4
#define FIVE PIN_B5
#define SIX PIN_B6
#define ENTER PIN_B7
#define SEVEN PIN_C0
#define EIGHT PIN_E1
#define NINE PIN_E2
#define ZERO PIN_D0
